### ISSUE TITLE
this is terribly slow, is this just me?

### ISSUE THREAD

**Issue by withinboredom** [ericmann/Redis-Object-Cache#14]
The overhead of the script is terribly slow, I see that I'm getting back my responses within milliseconds but for some reason it's insanely slow. I'm using the pecl extension with predis not present.

**Comment by rahul286** [comment]
@withinboredom I am in same boat. WordPress load time increases 8-10 times after using this object-cache.

I am using `php5-redis` library. 

Any clue why this makes wordpress slower rather than faster?

**Comment by Larceniii** [comment]
I agree; even with HHVM this is a net loss in performance, which makes no sense given how fast redis is.

**Comment by rahul286** [comment]
@Larceniii I shifted to https://github.com/alleyinteractive/wp-redis . The site I am testing is small so I did not feel any speed boost switching to redis with wp-redis plugin.

But I still wonder why this (Redis-Object-Cache) slowed down things so much that server crashed on so less load. As this plugin is more famous I suspect there is some edge case where peformance is degrading instead of improving.

Some debugging showed when using this (Redis-Object-Cache), php needed a lot more time to get/set keys/values from redis.

**Comment by macropin** [comment]
Yes, it does seem to make sites slower. My testing results with a very large Wordpress site (1.7G database). Page generation times for the home page of the blog without login:

No caching: 2-3 seconds
With this plugin: 20-22 seconds. No improvement on subsequent requests.

**Comment by enoch85** [comment]
Have you tried set it up with a unix socket instead? Add this to `wp-config.php` after you configured the backend. My site feels a lot more "snappy" now.

```
/** REDIS SOCKET */
define( 'WP_REDIS_SCHEME', 'unix' );
/** REDIS PATH TO SOCKET */
define( 'WP_REDIS_PATH', '/var/run/redis.sock' );
```
